### ISSUE TITLE
Null Pointer Exception when used with Multiverse

### ISSUE THREAD

**Issue by Scindix** [Lauriethefish/BetterPortals#1]
First of all thanks for developing this amazing plugin. These portals look and behave so much cooler.

BetterPortals doesn't seem to work well with [Multiverse](https://dev.bukkit.org/projects/multiverse-netherportals/) though. When using portals inside "world" or "world_nether" everything works as expected. However as soon as I'm using it in another overworld dimension (e.g. "second") nothing happens. The console spits out the following error message:

```[Server thread/ERROR]: Could not pass event PortalCreateEvent to BetterPortals v0.15
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.BlockPortal$Shape.createPortal(BlockPortal.java:342) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.BlockPortal.a(BlockPortal.java:60) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.BlockFire.onPlace(BlockFire.java:289) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:242) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:486) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-2f5d615-d07a78b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
        at com.lauriethefish.betterportals.PortalSpawnSystem.findSuitablePortalLocation(PortalSpawnSystem.java:50) ~[?:?]
        at com.lauriethefish.betterportals.events.PortalCreate.onPortalCreate(PortalCreate.java:82) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-2f5d615-d07a78b]
        ... 22 more
```

I have to add that I edited the bottom half of config.yml to include my "second" world:

```yaml
worldConnections:
  '0':
    originWorld: 'world'
    destinationWorld: 'world_nether'
    minSpawnY: 5
    maxSpawnY: 122
    coordinateRescalingFactor: 0.125
  '1':
    originWorld: 'world_nether'
    destinationWorld: 'world'
    minSpawnY: 5
    maxSpawnY: 250
    coordinateRescalingFactor: 8.0
  '2':
    originWorld: 'second'
    destinationWorld: 'second_nether'
    minSpawnY: 5
    maxSpawnY: 122
    coordinateRescalingFactor: 0.125
  '3':
    originWorld: 'second_nether'
    destinationWorld: 'second'
    minSpawnY: 5
    maxSpawnY: 250
    coordinateRescalingFactor: 8.0
```

Also the portals work fine without BetterPortals installed on my Server. I'm using Spigot 1.15.2 with 
Multiverse Core 4.1.0, Multiverse Inventories 3.0.0, Multiverse NetherPortals 4.1.1, Multiverse Portals 4.1.0 and Multiverse SignPortals 4.1.0. 

I'm willing to help if there is an issue to be fixed. However after digging into your source code I realized that I have no clue about the Spigot/Bukkit API. So you would at least have to point me in the right direction.

**Comment by Lauriethefish** [comment]
I'm looking into this now. Thanks for informing me

**Comment by Lauriethefish** [comment]
Ah, I think I found the cause of the issue. When multiverse loads, it creates all of the worlds, registering them with bukkit. Maybe BetterPortals is being loaded before multiverse, and therefore the worlds don't exist.

**Comment by Scindix** [comment]
> One question, when you start your server, is there any error loading the config? Since if there was that could explain the null value. Maybe multiverse worlds are treated differently server side, I'm not sure though.

No, no errors.

> Maybe BetterPortals is being loaded before multiverse, and therefore the worlds don't exist.

Yes it is. Infact the plugins seem to be loaded alphabetically.

> could you test this to see if it fixes it.

With your new version BetterPortals is loaded after Multiverse-Core. And as you suspected this fixes the issue. Everything works fine now!

Thank you very much for your fast response!

**Comment by Lauriethefish** [comment]
Glad to know this fixed your issue. I will be uploading this new version of the plugin to spigot soon, with a note about the bug.
