### ISSUE TITLE
Build Behind the portal. The server kicked me when I went up to the portal.

### ISSUE THREAD

**Issue by SpiderAang** [Lauriethefish/BetterPortals#117]
Photo: https://prnt.sc/26hx4s5
**Describe the bug**
When I went to the nether from the overworld and went up to the portal(Red square of the photo), the following error occurred.

**To Reproduce**
 I'm not entirely sure until I ask my friend, BUT when I went to the nether, in the green square of the photo it had a build and I think it's overworld. After the error the server threw me and when I logged in again the build had disappeared.

**Server Logs**
```
[08:22:40] [Server thread/ERROR]: [BetterPortals] A critical error occurred during plugin execution.
[08:22:40] [Server thread/ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[08:22:40] [Server thread/WARN]: com.lauriethefish.betterportals.shared.util.ReflectionException: java.lang.reflect.InvocationTargetException
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:247)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.nms.EntityUtil.getRawEntitySpawnPacket(EntityUtil.java:83)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:40)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTracker.addTracking(EntityTracker.java:157)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTrackingManager.setTracking(EntityTrackingManager.java:43)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateReplicatedEntities(PlayerEntityView.java:89)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:42)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
[08:22:40] [Server thread/WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[08:22:40] [Server thread/WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[08:22:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[08:22:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[08:22:40] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[08:22:40] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[08:22:40] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[08:22:40] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[08:22:40] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[08:22:40] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[08:22:40] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[08:22:40] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:22:40] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[08:22:40] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:22:40] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[08:22:40] [Server thread/WARN]:        at com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:245)
[08:22:40] [Server thread/WARN]:        ... 21 more
[08:22:40] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Markers should never be sent
[08:22:40] [Server thread/WARN]:        at net.minecraft.world.entity.Marker.getPacket(SourceFile:37)
[08:22:40] [Server thread/WARN]:        ... 26 more
[08:22:40] [Server thread/INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[08:22:40] [Server thread/INFO]: [BetterPortals] Disabling BetterPortals v0.10.2
[08:23:35] [Server thread/WARN]: SpiderAang was kicked for floating too long!
[08:23:35] [Server thread/INFO]: SpiderAang lost connection: Flying is not enabled on this server
[08:23:35] [Server thread/INFO]: SpiderAang left the game
[08:23:35] [Server thread/WARN]: handleDisconnection() called twice
```

**Additional context**
Plugin Version: BetterPortals-0.10.2
Game Version: 1.17.1

**Comment by Lauriethefish** [comment]
The steps to reproduce are pretty vague, if you could get your friend to describe exactly how I could recreate this situation in order to fix the bug, that'd be much better.

**Comment by Lauriethefish** [comment]
Going to close due to difficulty to reproduce
