### ISSUE TITLE
Could not pass event PlayerQuitEvent

### ISSUE THREAD

**Issue by sphings79** [Lauriethefish/BetterPortals#123]
**Describe the bug**
If a player disconnects or get kicked ou the quit event was not passed to your plugin

**To Reproduce**
just disconnect or get kicked

**Server Logs**
There are no other errors ecept this one
```
[11:42:54 ERROR]: Could not pass event PlayerQuitEvent to BetterPortals v0.10.2
java.lang.NullPointerException: Cannot invoke "com.lauriethefish.betterportals.bukkit.player.IPlayerData.getSelection()" because the return value of "java.util.Map.get(Object)" is null
	at com.lauriethefish.betterportals.bukkit.player.PlayerDataManager.onPlayerLeave(PlayerDataManager.java:158) ~[BetterPortals-0.10.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.heretere.hpwp.listener.HPWPRegisteredListener.callEvent(HPWPRegisteredListener.java:54) ~[HPWP.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:610) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:595) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1990) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1970) ~[?:?]
	at com.denizenscript.denizen.nms.v1_18.impl.network.handlers.AbstractListenerPlayInImpl.a(AbstractListenerPlayInImpl.java:108) ~[Denizen-1.2.3-b1758-REL.jar:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:712) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Additional context**
Plugin Version: BetterPortals version 0.10.2
Game Version: This server is running Paper version git-Paper-176 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b164899)```

**Comment by Lauriethefish** [comment]
I will need more context on this issue, since I cannot get it to happen when I disconnect.
