### ISSUE TITLE
Plugin Crash Upon Throwing Items into Portal

### ISSUE THREAD

**Issue by BestLovelyGod** [Lauriethefish/BetterPortals#132]
Log of crash:

```[12:48:33] [Server thread/WARN]: java.util.ConcurrentModificationException
[12:48:33] [Server thread/WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
[12:48:33] [Server thread/WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1612)
[12:48:33] [Server thread/WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1610)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.PortalEntityManager.handleTeleportation(PortalEntityManager.java:93)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.entity.PortalEntityManager.update(PortalEntityManager.java:71)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.portal.Portal.onUpdate(Portal.java:81)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.portal.PortalActivityManager.onPortalActivatedThisTick(PortalActivityManager.java:36)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.updateViewablePortals(PlayerData.java:92)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:108)
[12:48:33] [Server thread/WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1064)
[12:48:33] [Server thread/WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[12:48:33] [Server thread/WARN]:        at com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[12:48:33] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[12:48:33] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[12:48:33] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255)
[12:48:33] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428)
[12:48:33] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206)
[12:48:33] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034)
[12:48:33] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[12:48:33] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:48:33] [Server thread/INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[12:48:33] [Server thread/INFO]: [BetterPortals] Disabling BetterPortals v0.11.0```

**Comment by Lauriethefish** [comment]
Could I have some more information? What items? In what conditions?
This does not seem to happen to me.

**Comment by Lauriethefish** [comment]
Same issue as #114
