### ISSUE TITLE
Plugin Crash ...

### ISSUE THREAD

**Issue by Jeppa** [Lauriethefish/BetterPortals#134]
**Describe the bug**
When a dragon touches a portal the plugin crashes!

**To Reproduce**
Have a dragon touching a portal...

**Server Logs**
```
[18:26:15] [Server thread/ERROR]: [BetterPortals] A critical error occurred during plugin execution.
[18:26:15] [Server thread/ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[18:26:15] [Server thread/WARN]: com.lauriethefish.betterportals.shared.util.ReflectionException: java.lang.reflect.InvocationTargetException
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:247)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.nms.EntityUtil.getRawEntitySpawnPacket(EntityUtil.java:83)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:40)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.lambda$updateHiddenEntities$0(PlayerEntityView.java:68)
[18:26:15] [Server thread/WARN]: 	at java.base/java.util.Collection.removeIf(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateHiddenEntities(PlayerEntityView.java:64)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:40)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
[18:26:15] [Server thread/WARN]: 	at java.base/java.util.HashMap$Values.forEach(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[18:26:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[18:26:15] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:26:15] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:245)
[18:26:15] [Server thread/WARN]: 	... 21 more
[18:26:15] [Server thread/WARN]: Caused by: java.lang.UnsupportedOperationException
[18:26:15] [Server thread/WARN]: 	at net.minecraft.world.entity.boss.EntityComplexPart.S(EntityComplexPart.java:58)
[18:26:15] [Server thread/WARN]: 	... 25 more
[18:26:15] [Server thread/INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[18:26:15] [Server thread/INFO]: [BetterPortals] Disabling BetterPortals v0.11.0
[18:26:15] [Server thread/ERROR]: [BetterPortals] Error occurred while resetting player views
[18:26:15] [Server thread/WARN]: com.lauriethefish.betterportals.shared.util.ReflectionException: java.lang.reflect.InvocationTargetException
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:247)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.nms.EntityUtil.getRawEntitySpawnPacket(EntityUtil.java:83)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:40)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.lambda$onDeactivate$2(PlayerEntityView.java:114)
[18:26:15] [Server thread/WARN]: 	at java.base/java.util.HashMap.forEach(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.onDeactivate(PlayerEntityView.java:114)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.onDeactivate(PlayerPortalView.java:81)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.deactivateViews(PlayerData.java:117)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onPluginDisable(PlayerData.java:124)
[18:26:15] [Server thread/WARN]: 	at java.base/java.util.HashMap$Values.forEach(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.player.PlayerDataManager.onPluginDisable(PlayerDataManager.java:67)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.BetterPortals.onDisable(BetterPortals.java:151)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.shutdownPlugin(CrashHandler.java:28)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.processCriticalError(CrashHandler.java:23)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:62)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:26:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[18:26:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[18:26:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[18:26:15] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:26:15] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[18:26:15] [Server thread/WARN]: 	at BetterPortals-0.11.0.jar//com.lauriethefish.betterportals.shared.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:245)
[18:26:15] [Server thread/WARN]: 	... 26 more
[18:26:15] [Server thread/WARN]: Caused by: java.lang.UnsupportedOperationException
[18:26:15] [Server thread/WARN]: 	at net.minecraft.world.entity.boss.EntityComplexPart.S(EntityComplexPart.java:58)
[18:26:15] [Server thread/WARN]: 	... 30 more
```

**Additional context**
Plugin Version: 0.11.0
Game Version: 1.18.2  (Paper Build 260)

**Comment by Lauriethefish** [comment]
Fixed in 60a33d4
