### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by TaoXiaoBai** [Lauriethefish/BetterPortals#149]
**Describe the bug**
A critical error occurred during plugin execution.

**Server Logs**
[23:13:36 ERROR]: [BetterPortals] A critical error occurred during plugin execution.
[23:13:36 ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[23:13:36 WARN]: java.lang.IllegalArgumentException: Illegal rotation UP
[23:13:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.block.impl.CraftFloorSign.setRotation(CraftFloorSign.java:114)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.block.rotation.ModernBlockRotator.rotateByMatrix(ModernBlockRotator.java:19)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.block.bukkit.BukkitBlockMap.searchFromBlock(BukkitBlockMap.java:140)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.block.FloodFillBlockMap.updateInternal(FloodFillBlockMap.java:113)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.block.bukkit.BukkitBlockMap.updateInternal(BukkitBlockMap.java:314)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.block.FloodFillBlockMap.update(FloodFillBlockMap.java:102)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.portal.Portal.onViewUpdate(Portal.java:88)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.portal.PortalActivityManager.onPortalViewedThisTick(PortalActivityManager.java:51)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:77)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
[23:13:36 WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[23:13:36 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[23:13:36 WARN]:        at BetterPortals-0.11.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[23:13:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[23:13:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:13:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
[23:13:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[23:13:36 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[23:13:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[23:13:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[23:13:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:13:36 INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[23:13:36 INFO]: [BetterPortals] Disabling BetterPortals v0.11.1
[23:13:36 INFO]: [BetterPortals] Disconnecting from the proxy

**Additional context**
Plugin Version: v0.11.1
Game Version: 1.18.2

**Comment by Lauriethefish** [comment]
Fixed in above merged commits ^
