### ISSUE TITLE
Error occurred while resetting player views

### ISSUE THREAD

**Issue by tensiyoka** [Lauriethefish/BetterPortals#169]
Getting this error a little bit after the server come online.
```
- [Wed 14:43:07 ERROR BetterPortals] A critical error occurred during plugin execution.
- [Wed 14:43:07 ERROR BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
! [Wed 14:43:07 WARN ] java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "packet" is null
! [Wed 14:43:07 WARN ]     at ProtocolLib.jar//com.comphenix.protocol.events.PacketContainer.fromPacket(PacketContainer.java:157)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.nms.EntityUtil.getRawEntitySpawnPacket(EntityUtil.java:88)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:41)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28)
 
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.lambda$updateHiddenEntities$0(PlayerEntityView.java:69)
! [Wed 14:43:07 WARN ]     at java.base/java.util.Collection.removeIf(Collection.java:576)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateHiddenEntities(PlayerEntityView.java:65)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:41)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
! [Wed 14:43:07 WARN ]     at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
! [Wed 14:43:07 WARN ]     at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
! [Wed 14:43:07 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 14:43:07 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
! [Wed 14:43:07 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Wed 14:43:07 INFO  BetterPortals] Attempting to shut down the plugin . . .
  [Wed 14:43:07 INFO  BetterPortals] Disabling BetterPortals v0.12.1
- [Wed 14:43:07 ERROR BetterPortals] Error occurred while resetting player views
! [Wed 14:43:07 WARN ] java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "packet" is null
! [Wed 14:43:07 WARN ]     at ProtocolLib.jar//com.comphenix.protocol.events.PacketContainer.fromPacket(PacketContainer.java:157)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.nms.EntityUtil.getRawEntitySpawnPacket(EntityUtil.java:88)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:41)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.lambda$onDeactivate$2(PlayerEntityView.java:136)
! [Wed 14:43:07 WARN ]     at java.base/java.util.HashMap.forEach(HashMap.java:1421)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.onDeactivate(PlayerEntityView.java:136)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.onDeactivate(PlayerPortalView.java:81)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.deactivateViews(PlayerData.java:117)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onPluginDisable(PlayerData.java:124)
! [Wed 14:43:07 WARN ]     at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerDataManager.onPluginDisable(PlayerDataManager.java:67)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.BetterPortals.onDisable(BetterPortals.java:151)
! [Wed 14:43:07 WARN ]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
! [Wed 14:43:07 WARN ]     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
! [Wed 14:43:07 WARN ]     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.shutdownPlugin(CrashHandler.java:28)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.CrashHandler.processCriticalError(CrashHandler.java:23)
! [Wed 14:43:07 WARN ]     at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:62)
! [Wed 14:43:07 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 14:43:07 WARN ]     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
! [Wed 14:43:07 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
! [Wed 14:43:07 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Wed 14:43:28 INFO  Minecraft] CONSOLE issued server command: /list 
  [Wed 14:43:28 INFO ] default: Tensiyoka```

**Comment by Lauriethefish** [comment]
If you need more help with this problem, please create a new ticket using the issue format so that I have some more information about what type of server you are running, how to reproduce this (because it doesn't happen for me), etc.
