### ISSUE TITLE
purpur 1.19.3error

### ISSUE THREAD

**Issue by Shizuri23** [Lauriethefish/BetterPortals#180]
[00:49:51 ERROR]: [BetterPortals] A critical error occurred during plugin execution. 
[00:49:51 ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed. 
[00:49:51 WARN]: java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.PacketPlayOutMultiBlockChange 
[00:49:51 WARN]:  at java.base/java.util.Objects.requireNonNull(Objects.java:233) 
[00:49:51 WARN]:  at ProtocolLib-3.jar//com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:97) 
[00:49:51 WARN]:  at ProtocolLib-3.jar//com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:101) 
[00:49:51 WARN]:  at ProtocolLib-3.jar//com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:111) 
[00:49:51 WARN]:  at ProtocolLib-3.jar//com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:117) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.block.bukkit.MultiBlockChangeManager_1_16_2.sendChanges(MultiBlockChangeManager_1_16_2.java:70) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.block.PlayerBlockStates.resetAndUpdate(PlayerBlockStates.java:42) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.block.PlayerBlockView.onDeactivate(PlayerBlockView.java:104) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.onDeactivate(PlayerPortalView.java:79) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.setNotViewing(PlayerData.java:168) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:72) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111) 
[00:49:51 WARN]:  at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065) 
[00:49:51 WARN]:  at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) 
[00:49:51 WARN]:  at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47) 
[00:49:51 WARN]:  at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) 
[00:49:51 WARN]:  at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) 
[00:49:51 WARN]:  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500) 
[00:49:51 WARN]:  at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482) 
[00:49:51 WARN]:  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424) 
[00:49:51 WARN]:  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194) 
[00:49:51 WARN]:  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) 
[00:49:51 WARN]:  at java.base/java.lang.Thread.run(Thread.java:833) 
[00:49:51 INFO]: [BetterPortals] Attempting to shut down the plugin . . . 
[00:49:51 INFO]: [BetterPortals] Disabling BetterPortals v0.12.1

**Comment by rght925h** [comment]
Just a heads up: The same or a very similar issue seems to appear on Paper 1.19.3.
Tried this with https://github.com/Lauriethefish/BetterPortals/pull/179

> [Server thread/WARN]: [BetterPortals] Task #27 for BetterPortals v0.12.1-b8f38cd generated an exception
java.lang.ExceptionInInitializerError: null
        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:39) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTracker.addTracking(EntityTracker.java:156) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTrackingManager.setTracking(EntityTrackingManager.java:43) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateReplicatedEntities(PlayerEntityView.java:94) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:43) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:53) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-367]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-367]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-367]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-367]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-367]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-367]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-367]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.lauriethefish.betterportals.shared.util.ReflectionException: No method existed with given types in class net.minecraft.world.entity.Entity
        at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethodByTypes(ReflectionUtil.java:167) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethodByTypes(ReflectionUtil.java:137) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        at com.lauriethefish.betterportals.bukkit.nms.EntityUtil.<clinit>(EntityUtil.java:42) ~[BetterPortals-0.12.1-b8f38cd-all.jar:?]
        ... 20 more

**Comment by Lauriethefish** [comment]
1.19.3 is not supported at the moment
