### ISSUE TITLE
Paper 1.19.3 version 368 | Issue

### ISSUE THREAD

**Issue by PaladinFallen** [Lauriethefish/BetterPortals#181]
**Describe the bug**
Nothing visibly wrong with the portal works correctly however unable to see mobs through it, and [Server thread/WARN] and posting on the server side every time a player is around it.

**To Reproduce**
Move around or in and out of the portal

**Server Logs**
[13:38:24] [Server thread/WARN]: [BetterPortals] Task #94 for BetterPortals v0.12.1 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.lauriethefish.betterportals.bukkit.nms.EntityUtil
	at com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:41) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.lambda$updateHiddenEntities$0(PlayerEntityView.java:69) ~[BetterPortals-0.12.1.jar:?]
	at java.util.Collection.removeIf(Collection.java:576) ~[?:?]
	at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateHiddenEntities(PlayerEntityView.java:65) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:41) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111) ~[BetterPortals-0.12.1.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1073) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47) ~[BetterPortals-0.12.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-368]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-368]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception com.lauriethefish.betterportals.shared.util.ReflectionException: No method existed with given types in class net.minecraft.world.entity.Entity [in thread "Server thread"]
	at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethodByTypes(ReflectionUtil.java:167) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethodByTypes(ReflectionUtil.java:137) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.nms.EntityUtil.<clinit>(EntityUtil.java:50) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.showEntity(EntityPacketManipulator.java:41) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.entity.faking.IEntityPacketManipulator.showEntity(IEntityPacketManipulator.java:28) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTracker.addTracking(EntityTracker.java:157) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.entity.faking.EntityTrackingManager.setTracking(EntityTrackingManager.java:43) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateReplicatedEntities(PlayerEntityView.java:94) ~[BetterPortals-0.12.1.jar:?]
	at com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:43) ~[BetterPortals-0.12.1.jar:?]
	... 14 more

**Additional context**
Plugin Version: 0.12.1
Game Version:Paper 1.19.3 version 368

Same error in issue #180 on the paper side

**Comment by Lauriethefish** [comment]
1.19.3 is not supported at the moment

**Comment by mrsqueak11806** [comment]
I'm having the same bug. Will 1.19.3 support be incoming?

**Comment by Lauriethefish** [comment]
No, I have no plans to update BP in the future.

**Comment by mijofa** [comment]
Using 1.19.4 I had the same issue and was able to workaround the errors in the logs by just setting `enableEntitySupport: false` in the config.

I was still running into an issue with concurrent users, and/or Geyser support, not sure, need to gather more info before I make a bug report. But I did get **this** one worked around now problem at all.
