### ISSUE TITLE
Linking worlds error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Lauriethefish/BetterPortals#186]
[14:03:22] [Server thread/ERROR]: [BetterPortals] Please create an issue at https://github.com/Lauriethefish/BetterPortals/issues to get this fixed.
[14:03:22] [Server thread/WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[14:03:22] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[14:03:22] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:289)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityPacketManipulator.sendAddPlayerProfile(EntityPacketManipulator.java:391)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityTracker.addTracking(EntityTracker.java:154)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.entity.faking.EntityTrackingManager.setTracking(EntityTrackingManager.java:43)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.updateReplicatedEntities(PlayerEntityView.java:94)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.entity.PlayerEntityView.update(PlayerEntityView.java:43)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.view.PlayerPortalView.update(PlayerPortalView.java:68)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.updatePortalViews(PlayerData.java:79)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.player.PlayerData.onUpdate(PlayerData.java:111)
[14:03:22] [Server thread/WARN]: 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[14:03:22] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[14:03:22] [Server thread/WARN]: 	at BetterPortals-0.12.1.jar//com.lauriethefish.betterportals.bukkit.tasks.MainUpdate.run(MainUpdate.java:47)
[14:03:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[14:03:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:03:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[14:03:22] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[14:03:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[14:03:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[14:03:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:03:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:03:22] [Server thread/INFO]: [BetterPortals] Attempting to shut down the plugin . . .
[14:03:22] [Server thread/INFO]: [BetterPortals] Disabling BetterPortals v0.12.1

**Comment by TDMidkwhatisxd** [comment]
This is the config  

worldConnections:
 '0':
  originWorld: 'world2'
  destinationWorld: 'world2_nether'
  minSpawnY: 5 # Leave blank for automatically set to world size
  maxSpawnY: 122 # Leave blank for automatically set to world size
  coordinateRescalingFactor: 0.125
 '1':
  originWorld: 'world2_nether'
  destinationWorld: 'world2'
  minSpawnY: 5 # Leave blank for automatically set to world size
  maxSpawnY: 250 # Leave blank for automatically set to world size
  coordinateRescalingFactor: 8.0
 '2':
  originWorld: 'world3'
  destinationWorld: 'world3_nether'
  minSpawnY: 5 # Leave blank for automatically set to world size
  maxSpawnY: 122 # Leave blank for automatically set to world size
  coordinateRescalingFactor: 0.125
 '3':
  originWorld: 'world3_nether'
  destinationWorld: 'world3'
  minSpawnY: 5 # Leave blank for automatically set to world size
  maxSpawnY: 250 # Leave blank for automatically set to world size
  coordinateRescalingFactor: 8.0
