### ISSUE TITLE
Draconic Evolution Dislocator Crash

### ISSUE THREAD

**Issue by FreezePhoenix** [Lauriethefish/BetterPortals#47]
**Describe the bug**

Using a dislocator from Draconic Evolution that results in cross-dimension travel (In multiplayer) causes the game to effectively force the player into an endless connecting state. They're unable to move, or see any blocks, and cannot be moved by other players (but are able to be moved by other means, such as pistons). *Any* attempt to reload their view (Lowering the render distance, exiting the server) results in the server crashing and the client being disconnected.

Disabling third party transitions did not resolve the issue.

**To Reproduce**

Start a LAN world, connect to it with a second client, create a dislocator pair, give each player one of the dislocators from the pair, move the client (or the host) to another dimension, and attempt to teleport from either one to the other.

**Server Logs**

When the dislocator is used:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerChunkMap.handler$zci000$updateMovingPlayerWithViews(PlayerChunkMap.java:798) ~[ou.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72685_d(PlayerChunkMap.java) ~[ou.class:?]
	at net.minecraft.server.management.PlayerList.func_72358_d(PlayerList.java:383) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:584) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18) ~[lk$b.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more
```
Further attempts to use the dislocator will result in an identical error (But not crash the server).

Attempting to leave the server or lower render distance results in the following error, crashing the server:
```
java.lang.IllegalStateException: Player changed world without us noticing. Did some third-party mod do something weird?
	at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:67) ~[ServerWorldsManagerImpl.class:?]
	at net.minecraft.server.management.PlayerChunkMap.handler$zci000$setPlayerViewRadiusWithViews(PlayerChunkMap.java:817) ~[ou.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_152622_a(PlayerChunkMap.java) ~[ou.class:?]
	at net.minecraft.server.management.PlayerList.func_152611_a(PlayerList.java:1155) ~[pl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:284) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Additional context**
Plugin Version: 0.3.7.7
Game Version: Forge 14.23.5.2854

**Comment by FreezePhoenix** [comment]
I'm sorry, I was not aware that this was the wrong github repository.
