### ISSUE TITLE
Exception when passing the portal, but not critical

### ISSUE THREAD

**Issue by popos123** [Lauriethefish/BetterPortals#98]
**Describe the bug**
Just throwing the exception when passing the portal, but server still working fine.

**To Reproduce**
Just pass the connected portal on the spigot / bukkit server. MC version 1.18

**Server Logs**
```
[02:04:48] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BetterPortals v0.9.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:186) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1472) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1157) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1136) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1129) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:110) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1112) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1037) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.lauriethefish.betterportals.shared.util.ReflectionUtil$ReflectionException: java.lang.NoSuchMethodException: Method hasTag does not exist in net.minecraft.world.item.ItemStack
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethod(ReflectionUtil.java:146) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:171) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:195) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:206) ~[?:?]
at com.lauriethefish.betterportals.bukkit.util.nms.NBTTagUtil.hasMarkerTag(NBTTagUtil.java:67) ~[?:?]
at com.lauriethefish.betterportals.bukkit.config.MessageConfig.isPortalWand(MessageConfig.java:161) ~[?:?]
at com.lauriethefish.betterportals.bukkit.events.SelectionEvents.onPlayerInteract(SelectionEvents.java:33) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor424.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
... 23 more
Caused by: java.lang.NoSuchMethodException: Method hasTag does not exist in net.minecraft.world.item.ItemStack
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.findMethod(ReflectionUtil.java:146) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:171) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:195) ~[?:?]
at com.lauriethefish.betterportals.shared.util.ReflectionUtil.runMethod(ReflectionUtil.java:206) ~[?:?]
at com.lauriethefish.betterportals.bukkit.util.nms.NBTTagUtil.hasMarkerTag(NBTTagUtil.java:67) ~[?:?]
at com.lauriethefish.betterportals.bukkit.config.MessageConfig.isPortalWand(MessageConfig.java:161) ~[?:?]
at com.lauriethefish.betterportals.bukkit.events.SelectionEvents.onPlayerInteract(SelectionEvents.java:33) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor424.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
```
... 23 more

**Additional context**
Plugin Version: 0.9.0
Game Version: 1.18.0

**Comment by Lauriethefish** [comment]
Minecraft version 1.18 isn't currently supported.
